package finalproject.user;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import finalproject.config.IoCon;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author ma7moud
 */
public class ChangeInformation extends javax.swing.JPanel {
    private Socket mSocket;
    /**
     * Creates new form ChatRoomPanel
     */
    public ChangeInformation() {
        initComponents();
        mSocket = IoCon.getInstance().getmSocket();
        mSocket.on("change feed", changeFeedBack);
        un.setEnabled(false);
        oldPass.setEnabled(false);
        newPass.setEnabled(false);
        newPassV.setEnabled(false);
    }
     private Emitter.Listener changeFeedBack = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            String msg = (String) args[0];
                 JOptionPane.showMessageDialog(null, msg);
    }};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        oldPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newPassV = new javax.swing.JTextField();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(227, 242, 253));
        setPreferredSize(new java.awt.Dimension(600, 701));
        setLayout(null);

        id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add(id);
        id.setBounds(270, 10, 230, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(130, 130, 90, 50);

        un.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        add(un);
        un.setBounds(260, 130, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Old Password");
        add(jLabel3);
        jLabel3.setBounds(120, 210, 90, 50);

        oldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(oldPass);
        oldPass.setBounds(260, 210, 190, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("New Password");
        add(jLabel4);
        jLabel4.setBounds(120, 290, 90, 50);

        newPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(newPass);
        newPass.setBounds(260, 290, 190, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("vierfiy Password");
        add(jLabel5);
        jLabel5.setBounds(120, 370, 110, 50);

        newPassV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(newPassV);
        newPassV.setBounds(260, 370, 190, 50);

        rb2.setBackground(new java.awt.Color(227, 242, 253));
        rb2.setText("Password");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        add(rb2);
        rb2.setBounds(360, 90, 90, 23);

        rb1.setBackground(new java.awt.Color(227, 242, 253));
        rb1.setText("username");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        add(rb1);
        rb1.setBounds(260, 90, 90, 23);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("What to change ?");
        add(jLabel6);
        jLabel6.setBounds(120, 90, 120, 30);

        jButton2.setBackground(new java.awt.Color(227, 242, 253));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_save_black_18dp.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(390, 430, 60, 50);

        jButton3.setBackground(new java.awt.Color(227, 242, 253));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_cancel_18pt_3x.png"))); // NOI18N
        add(jButton3);
        jButton3.setBounds(300, 430, 50, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(checkData()){
            sendData();
        }
        else{
            JOptionPane.showMessageDialog(this, "You Should Verify Your Password Correctly");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        if(!un.isEnabled()){
            un.setEnabled(true);
        }
        else{
            un.setEnabled(false);
        }
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        if(!oldPass.isEnabled()){
        oldPass.setEnabled(true);
        newPass.setEnabled(true);
        newPassV.setEnabled(true);
        }
        else{
        oldPass.setEnabled(false);
        newPass.setEnabled(false);
        newPassV.setEnabled(false);
        }
    }//GEN-LAST:event_rb2ActionPerformed
    private boolean checkData(){
        boolean check = false;
        if(un.isEnabled() && !oldPass.isEnabled()){
            check = true;
        }
        else if(oldPass.isEnabled()){
            if(newPassV.getText().equals(newPass.getText())){
                check = true;
            }
            else{
                oldPass.setText("");
                newPass.setText("");
                newPassV.setText("");
                check = false;
            }
        }
        return check;
    }
    
    private void sendData(){
        JSONObject data=new JSONObject();
        if(un.isEnabled() && !oldPass.isEnabled()){
        try{
            data.put("id",id.getText());
            data.put("type", 1);
            data.put("uname",un.getText());
           }catch(Exception ex){}
            }else if(oldPass.isEnabled() && !un.isEnabled()){
        try{
            data.put("id",id.getText());
            data.put("type", 2);
            data.put("oldpass",oldPass.getText());
            data.put("newpass",newPass.getText());
           }catch(Exception ex){}
            }else{
        try{
            data.put("id",id.getText());
            data.put("type", 3);
            data.put("uname",un.getText());
            data.put("oldpass",oldPass.getText());
            data.put("newpass",newPass.getText());
           }catch(Exception ex){}
            }
            mSocket.emit("change", data);
    }
    
    public void data(String ID,String username){
        id.setText(ID);
        un.setText(username);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField newPassV;
    private javax.swing.JTextField oldPass;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
