package finalproject.user;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import finalproject.config.IoCon;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.awt.AlphaComposite;
import java.awt.Composite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author ma7moud
 */
public class EditData extends javax.swing.JPanel {
private Socket mSocket = IoCon.getInstance().getmSocket();
    protected String mRoomname,mUsername;
    public boolean talock = false;
    ImageIcon icon = new ImageIcon("depositphotos_80914334-Science-concept-Computer-Science-in-grunge-dark-room.jpg"); 
    /**
     * Creates new form ChatRoomPanel
     */
    public void setRoomname(String roomname,String user) {
        mUsername=user;
        mRoomname = roomname;
        JSONObject data=new JSONObject();
try{
    data.put("room", roomname);
    }catch(Exception ex){}
    mSocket.emit("enterroom" , data);
    }
    
    public EditData() {
        initComponents();
        jLabel1.setIcon(icon);
        mSocket.on("new message", onNewMessage);
        
        
        this.addContainerListener(new java.awt.event.ContainerListener(){
        public void componentRemoved(java.awt.event.ContainerEvent e) {
        PanelClosed(e);
    }
        public void componentAdded(java.awt.event.ContainerEvent e) {
        
    }
        

        private void PanelClosed(java.awt.event.ContainerEvent e){
            JSONObject data=new JSONObject();
try{
    data.put("room", mRoomname);
    mSocket.emit("roomleft",data);
    }catch(Exception ex){}
        }
        
    });
        
    }
    
    private Emitter.Listener onNewMessage = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    JSONObject data = (JSONObject) args[0];
                    String username;
                    String message;
                    String roomName;
                    try {
                        username = data.getString("username");
                        message = data.getString("message");
                        roomName=data.getString("roomname");
                    } catch (JSONException e) {
                        return;
                    }
                    if(roomName.equals(mRoomname)){
                    jTextArea1.append(username+":"+message);
                    }
        }};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane(){
            @Override
            protected void paintComponent(Graphics g) {
                try {
                    Composite composite = ((Graphics2D)g).getComposite();

                    ((Graphics2D)g).setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.8f));
                    g.setColor(getBackground());
                    g.fillRect(0, 0, getWidth(), getHeight());

                    ((Graphics2D)g).setComposite(composite);
                    paintChildren(g);
                }
                catch(IndexOutOfBoundsException e) {
                    super.paintComponent(g);
                }
            }
        };
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(227, 242, 253));
        setPreferredSize(new java.awt.Dimension(600, 701));
        setLayout(null);

        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 620, 420);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(0, 430, 510, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_chat_18pt_3x.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(510, 430, 110, 59);
        add(jLabel1);
        jLabel1.setBounds(-170, -10, 790, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        talock = true;
        jTextArea1.append("You "+":"+jTextField5.getText()+"\n");
        sendd();
        talock = false;
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        talock = true;
        jTextArea1.append("You "+":"+jTextField5.getText()+"\n");
        sendd();
        talock = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    void sendd(){
        JSONObject data=new JSONObject();
try{
    data.put("room", mRoomname);
    data.put("message", jTextField5.getText()+"\n");
    }catch(Exception ex){
    
    }
        
        jTextField5.setText("");
        
mSocket.emit("new message", data );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

//    WindowListener l = new WindowAdapter() {
//	    public void windowClosing(WindowEvent e) {
//                JSONObject data=new JSONObject();
//try{
//    data.put("room", mRoomname);
//    mSocket.emit("roomleft",data);
//    }catch(Exception ex){}
//                
//                }
//	};
    
}
