package finalproject.user;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import io.socket.client.Socket;

import finalproject.config.IoCon;
import io.socket.emitter.Emitter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Skool
 */
public class UserLog extends javax.swing.JFrame {
Socket mSocket = IoCon.getInstance().getmSocket();
    private String user;
    private String id;
    ImageIcon img = new ImageIcon("ic_chat_bubble_outline_white_48pt_3x.png");
    /**
     * Creates new form UserLog
     */
    public UserLog() {
        initComponents();
        this.setSize(335,243);
        this.setLocationRelativeTo(null);
        this.setIconImage(img.getImage());
        mSocket.on("logged", onUserJoined);
        mSocket.on("notlog", onUsernotLog);
    }
    
    private Emitter.Listener onUsernotLog = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    String pass = (String) args[0];

                    popup(pass);
        }};

    
    private Emitter.Listener onUserJoined = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    try {
                        
                        JSONObject data = (JSONObject) args[0];
                        String username;
                        
                        try {
                            username = data.getString("username");
                        } catch (JSONException e) {
                            return;
                        }
                        verify(data);
                    } catch (JSONException ex) {
                    }
        }};
    
   private void popup(String pass){
        if(pass.equals("notf")){
        JOptionPane.showMessageDialog(null, "Wrong Username or Password");
        }else{
            JOptionPane.showMessageDialog(null, pass);
        }
    }
   private void verify(JSONObject username) throws JSONException{
        UserMainFrame mf = new UserMainFrame();
        mf.sendSo(id,username);
        mf.setLocationRelativeTo(this);
        this.setVisible(false);
        mf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(79, 195, 247));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 40, 163, 47);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 124, 47);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 124, 47);

        jPasswordField1.setBackground(new java.awt.Color(79, 195, 247));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 110, 163, 47);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_exit_to_app_black_36dp.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 160, 57, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/gradient-blue-red-background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
       sendData();
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    private void sendData(){
            JSONObject data=new JSONObject();
try{
    data.put("type", "user");
    data.put("userid", jTextField1.getText());
    data.put("pass", jPasswordField1.getText());
    id = jTextField1.getText();
}
catch(Exception ex){}
        mSocket.emit("login",data );      
        jTextField1.setText("");
        jPasswordField1.setText("");
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
