package finalproject.admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import finalproject.config.IoCon;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author ma7moud
 */
public class ActiveRooms extends javax.swing.JPanel {
String roomname="";
String ActiveRoom="";
    /**
     * Creates new form ActiveRooms
     */
    public ActiveRooms() {
        initComponents();
        JScrollPane s;
        ButtonGroup group=new ButtonGroup();
        group.add(jToggleButton1);
        group.add(jToggleButton2);
        group.add(jToggleButton3);
        group.add(jToggleButton4);
        group.add(jToggleButton5);
        group.add(jToggleButton6);
        group.add(jToggleButton7);
        group.add(jToggleButton8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 71, 161));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        jPanel2.setBackground(new java.awt.Color(13, 71, 161));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_videocam_black_18dp.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(170, 60, 80, 60);

        jToggleButton2.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_speaker_phone_black_18dp.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2);
        jToggleButton2.setBounds(90, 60, 80, 60);

        jToggleButton3.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_desktop_mac_black_36dp.png"))); // NOI18N
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3);
        jToggleButton3.setBounds(10, 60, 80, 60);

        jToggleButton4.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_language_black_18dp.png"))); // NOI18N
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton4);
        jToggleButton4.setBounds(90, 10, 80, 50);

        jToggleButton5.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_all_inclusive_black_18dp.png"))); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton5);
        jToggleButton5.setBounds(10, 10, 80, 50);

        jToggleButton6.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_local_library_black_18dp.png"))); // NOI18N
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton6);
        jToggleButton6.setBounds(250, 10, 80, 50);

        jToggleButton7.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_rate_review_18pt_3x.png"))); // NOI18N
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton7);
        jToggleButton7.setBounds(250, 60, 80, 60);

        jToggleButton8.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_build_black_18dp.png"))); // NOI18N
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton8);
        jToggleButton8.setBounds(170, 10, 80, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.inactiveCaption);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Active Rooms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(985, 985, 985))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed

        setRoomname("Public");        
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
      setRoomname("SCI");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
      setRoomname("IT");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       setRoomname("TCOM");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
       setRoomname("ENG");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        setRoomname("GIS");        
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
      setRoomname("KM");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
       setRoomname("ARCH");
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed
 private Socket mSocket = IoCon.getInstance().getmSocket();

    public void setRoomname(String roomname) {
    if(!ActiveRoom.equals("")){
               JSONObject data=new JSONObject();
try{
    data.put("room", ActiveRoom);
    mSocket.emit("roomleft",data);
    }catch(Exception ex){
    
    }
}
        mSocket.on("new message", onNewMessage);        
        this.roomname = roomname;
        JSONObject data=new JSONObject();
try{
    data.put("room", roomname);
    }catch(Exception ex){}

    mSocket.emit("enterroom" , data);
    ActiveRoom=roomname;
    }
    
    private Emitter.Listener onNewMessage = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    JSONObject data = (JSONObject) args[0];
                    String username;
                    String message;
                    String roomName;
                    try {
                        username = data.getString("username");
                        message = data.getString("message");
                        roomName=data.getString("roomname");
                    } catch (JSONException e) {
                        return;
                    }
                    if(roomName.equals(roomname)){
                    jTextArea1.append(username+":"+message);
                    jTextArea1.append("\n");
                    }
        }};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    // End of variables declaration//GEN-END:variables
}
