package finalproject.admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import finalproject.config.IoCon;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;


public class AdminMainForm extends javax.swing.JFrame {
 private ArrayList al = new ArrayList();
    Socket mSocket;
    String myID;
    ImageIcon img = new ImageIcon("ic_airline_seat_recline_normal_white_48pt_3x.png");
    JSONArray jrlist;
    /**
     * Creates new form AdminMainForm
     */
    public AdminMainForm() {
        initComponents();
         setSize(800,700);
        setLocationRelativeTo(null);
        bar1.setBackground(new Color(25,118,210));
        basePanel.setSize(800,800);
              mSocket = IoCon.getInstance().getmSocket();
        mSocket.on("user left", onUserLeft);
  this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ButtonGroup group=new ButtonGroup();
        group.add(jToggleButton1);
        group.add(jToggleButton2);
        group.add(jToggleButton3);
        group.add(jToggleButton4);
        this.setIconImage(img.getImage());
    }
    public void sendSo(JSONObject data , String ID) throws JSONException{
    myID = ID;
   JSONArray onlineList = data.getJSONArray("jarr");
   // DefaultListModel model = new DefaultListModel();
    for(int i=0;i<onlineList.length();i++){
            JSONObject e = onlineList.getJSONObject(i);
            String id =  e.getString("id");
            if(!myID.equals(id))
            al.add(id);
          //   model.addElement(e.getString("name"));
           // tas.append(id+"\n");
            System.out.println(id+"\n");       
    }        }
        private Emitter.Listener onUserLeft = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            try {
                JSONArray username = (JSONArray) args[0];
                jrlist = username;
                    //DefaultListModel model = new DefaultListModel();
                     if(!al.isEmpty())
                     al.clear();
                    for(int i=0;i<username.length();i++){
                        JSONObject e = username.getJSONObject(i);
                        String id =  e.getString("id");
                        if(!myID.equals(id))
                        al.add(id);
                       // model.addElement(e.getString("name"));
                       // System.out.println(id+"\n");
                    }
         
            } catch (JSONException ex) {
                
            }
                 
    }};
public void changePanel(JPanel mee){

        basePanel.removeAll();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );// TODO add your handling code here:

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(mee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                ));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bar1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        basePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin monitor");
        getContentPane().setLayout(null);

        bar.setLayout(null);

        jButton1.setBackground(new java.awt.Color(25, 118, 210));
        bar.add(jButton1);
        jButton1.setBounds(70, 0, 73, 70);

        jButton4.setBackground(new java.awt.Color(25, 118, 210));
        bar.add(jButton4);
        jButton4.setBounds(140, 0, 73, 70);

        jButton5.setBackground(new java.awt.Color(25, 118, 210));
        bar.add(jButton5);
        jButton5.setBounds(0, 0, 73, 70);

        getContentPane().add(bar);
        bar.setBounds(0, 0, 0, 0);

        bar1.setMinimumSize(new java.awt.Dimension(800, 100));
        bar1.setRequestFocusEnabled(false);
        bar1.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_settings_white_18pt_3x.png"))); // NOI18N
        jToggleButton1.setPreferredSize(new java.awt.Dimension(200, 23));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        bar1.add(jToggleButton1);
        jToggleButton1.setBounds(500, 0, 160, 100);

        jToggleButton2.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_person_add_white_36dp.png"))); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(200, 23));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        bar1.add(jToggleButton2);
        jToggleButton2.setBounds(340, 0, 160, 100);

        jToggleButton3.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_insert_chart_white_18pt_3x.png"))); // NOI18N
        jToggleButton3.setPreferredSize(new java.awt.Dimension(200, 23));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        bar1.add(jToggleButton3);
        jToggleButton3.setBounds(170, 0, 170, 100);

        jToggleButton4.setBackground(new java.awt.Color(25, 118, 210));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_not_interested_white_36dp.png"))); // NOI18N
        jToggleButton4.setPreferredSize(new java.awt.Dimension(200, 23));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        bar1.add(jToggleButton4);
        jToggleButton4.setBounds(0, 0, 170, 100);

        jButton2.setBackground(new java.awt.Color(25, 118, 210));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/ic_power_settings_new_white_48pt.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bar1.add(jButton2);
        jButton2.setBounds(660, 0, 140, 100);

        getContentPane().add(bar1);
        bar1.setBounds(0, 0, 800, 100);

        basePanel.setBackground(new java.awt.Color(13, 71, 161));
        basePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(basePanel);
        basePanel.setBounds(0, 100, 800, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
      changePanel(new StudentsOnline(jrlist , myID));  
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        changePanel(new ActiveRooms());  // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
     changePanel(new AddUsers());     // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
     mSocket.off("modifyfeed");
        mSocket.off("submitdata");
        changePanel(new MangeUsers());
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

this.setVisible(false);
new AdminLogIn().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bar1;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
