package finalproject.admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import finalproject.config.IoCon;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author User
 */
public class AdminLogIn extends javax.swing.JFrame {
    private Socket mSocket = IoCon.getInstance().getmSocket();
    private String user;
    private String id ;
    /**
     * Creates new form AdminLogIn
     */
    public AdminLogIn() {
        initComponents();
        this.setSize(293, 210);
        this.setLocationRelativeTo(null);
        mSocket.on("logged", onUserJoined);
        mSocket.on("notlog", onUsernotLog);
    }
    
    private Emitter.Listener onUsernotLog = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    String pass = (String) args[0];

                    popup(pass);
        }};

    
    private Emitter.Listener onUserJoined = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            
                    JSONObject data = (JSONObject) args[0];
                    String username;
                    
                    try {
                        username = data.getString("username");
                        user = username;
                    } catch (JSONException e) {
                        return;
                    }
                    verify(username,data);
        }};
    
    private void popup(String pass){
        if(pass.equals("wrong")){
        JOptionPane.showMessageDialog(null, "Wrong Username or Password");
        }else{
            JOptionPane.showMessageDialog(null, pass);
        }
    }
    private void verify(String adminName,JSONObject data){
        try {
            String userName = adminName;
            AdminMainForm am = new AdminMainForm();
            am.sendSo(data , id);
            am.setLocationRelativeTo(this);
            this.setVisible(false);
            am.setVisible(true);
        } catch (JSONException ex) {
            Logger.getLogger(AdminLogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login");
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);
        getContentPane().add(UserField);
        UserField.setBounds(100, 40, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 60, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 130, 73, 23);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(100, 80, 110, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalDesign/icons/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 310, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JSONObject data=new JSONObject();
try{
    data.put("type", "admin");
    data.put("userid", UserField.getText());
    data.put("pass", PasswordField.getText());
    //id = UserField.getText();
}
catch(Exception ex){}
        mSocket.emit("login",data );      
        UserField.setText("");
        PasswordField.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        JSONObject data=new JSONObject();
try{
    data.put("type", "admin");
   data.put("userid", UserField.getText());
    data.put("pass", PasswordField.getText());
    id = UserField.getText();
}
catch(Exception ex){}
        mSocket.emit("login",data );      
        UserField.setText("");
        PasswordField.setText("");
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
